### ISSUE TITLE
REQUEST: Port to Classic

### ISSUE THREAD

**Issue by Bak3y** [Bak3y/JPostal#1]
Requested by [farnkrchamp](https://www.curseforge.com/members/farnkrchamp) on Curseforge

**Comment by Bak3y** [comment]
@jonny8909 any idea on the level of effort here?

**Comment by Bak3y** [comment]
This appears to be a decent resource on changes. 

https://wow.gamepedia.com/Porting_addons_to_Classic

**Comment by jonny8909** [comment]
> @jonny8909 any idea on the level of effort here?

No idea at the moment, I've never even opened/played classic. When I get a chance I will fire it up and have a look at the API.

**Comment by Bak3y** [comment]
If it's not something we want to support, we can just close this as won't fix.

**Comment by jonny8909** [comment]
Let's close it as a won't fix for now.
I did fire up classic and some of it seems to work but I have no real way of testing anything I write against in a practical way
